DP-6517 create ajax pattern to allow client side rendering of other patterns (#644)
* Create new pattern: ajax-alerts organism

* Use new ajax-alerts pattern on guide page

* Stub out ajax alerts module, templates; create handlebarsHelpers

* Copy emergency alerts json to public in gulp copy task

* Make alerts js listeners work on dom load

- Add empty state scaffolding for emergency alerts org
- Create handlebars templates for molecules
- Move logic to ajax alerts JS
- Hide organism by default

* Make ajax alerts use passed in endpoint

* Allow emergency alert js to wait for ajax alert js to set id for cookie

* Add docs and error handling

* Add docs for ajax alerts organism

* DP-6517: A custom jQuery plugin for alerts

This updates the alerts ajax functionality by allowing it to be
more easily overridden, passing in a transform function that can
be used to alter the data between the endpoint and the render
process.

* DP-6517: Alerts: make default endpoint relative

* DP-6517: Demonstrate alert providing transform

* Install twigjs to handle client side rendering of twig templates

See: https://github.com/twigjs/twig.js/wiki

* Copy twig templates into /public on gulp build

So we can access them via ajax to render clientside

* Update global ma object with path to twig patterns

This will have to be emulated per implementation

* Rename ajaxAlert to ajaxPattern to indicate broader use cases

* Update ajaxPattern jQuery plugin to use twigJS

@todo validate data against a schema: https://github.com/tdegrunt/jsonschema

* Initialize accordion/emergency/header alerts js on twigjs render

* Stub out header-alerts pattern to iterate over array of headerAlerts

@todo document

* Create endpoint for header alerts

* Implement ajax emergendy / header alerts on various pages/templates

* Include twigJS in readme

* Remove unused json data

* Clean up ajaxPattern jQuery plugin

* Remove handlebars helper import since we are using twigJS

* Let path to pattern subdirectories be configurable per implementation

* Allow emergency alerts and informational notices via alert title prefix

* Only copy pattern twig in gulp task

* Only attempt to fetch twig template if there is data for pattern

* Code cleanup.

* Code cleanup.

* Remove handlebars templates for emergency alert

* Use twigjs asynchronously

* Add comment re: subsequent synchronous pattern loads

* Update babelify in attempt to fix error 

Error when attempting to load ajax pattern for alerts using twigJS:

TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.remoteFunction (<anonymous>:2:14)
    at new e.Template (http://mass.local/themes/custom/mass_theme/js/vendor-generated.js?ozo1ig:10:18811)
    at XMLHttpRequest.<anonymous> (http://mass.local/themes/custom/mass_theme/js/vendor-generated.js?ozo1ig:12:21270)
    at XMLHttpRequest.s.onreadystatechange (http://mass.local/themes/custom/mass_theme/js/vendor-generated.js?ozo1ig:12:2380)

Saw the same error referenced in several projects where people recommended updating babel...

* Update nodejs version for circle

* Enforce node-sass to build binding for node environment

* Code cleanup. (to trigger another build)

* Revert "Update babelify in attempt to fix error "

This reverts commit 95edee9c92ab8459729486d8dc85063d24f7703b.

* Revert "Update nodejs version for circle"

This reverts commit a5623d583b493fdd22eecea92f0268b01cf21a0c.

* Revert "Enforce node-sass to build binding for node environment"

This reverts commit ea538c12b3afa64369544ab2d5005f4364c12b9e.

* Revert "Code cleanup. (to trigger another build)"

This reverts commit aa53776b7e15e8e22453a7d21935243fd15da809.

* Add informational site alerts variant

* Add header alert as notice variant.

* Document header alerts organism 

This is just an array of header alert organisms, but necessary in order to be able to render a single pattern which iterates through a data structure for twigjs.

* Show placeholder for header alert prefix in pattern json

* Update ajax override transform docs to indicate: return { } when no data

* Fix typos.

* Add logic to templates which include ajaxPattern for alerts

* Stub out alert content type, pages

* Add gulp-copy as dependency

So that we have the option to remove parts of the source path and rename _patterns to patterns

_patterns was not browseable by github pages, so all Twigjs render ajax calls were returning 404 errors

* Update gulp copyTwig task to use public/assets/  patterns/ vs _patterns/

* Make TwigJS work in production

- Update js path to twig patterns for TwigJS
- Configure gulp uglify to retain var/function names

* Document alert template and pages

* Update ajax pattern override example to transform data but not overwrite

* Remove handlebars updates since we are using twigJS